const { FlatCompat } = require("@eslint/eslintrc");
const js = require("@eslint/js");
const tsParser = require("@typescript-eslint/parser");
const tsPlugin = require("@typescript-eslint/eslint-plugin");
const reactHooksPlugin = require("eslint-plugin-react-hooks");

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

module.exports = [
  // Ignore build output and dependencies (so "eslint ." is usable)
  { ignores: ["build/**", "node_modules/**", "functions/node_modules/**", "*.min.js"] },
  // TypeScript/TSX: use TypeScript parser so "as const", types, etc. are understood
  {
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
    },
    plugins: { "@typescript-eslint": tsPlugin },
    rules: tsPlugin.configs.recommended.rules,
  },
  // Base: ESLint recommended + browser globals (no react-app — it breaks under ESLint 10 flat config)
  {
    files: ["**/*.{js,jsx,mjs,cjs,ts,tsx}"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
      globals: {
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        alert: "readonly",
        confirm: "readonly",
        prompt: "readonly",
        console: "readonly",
        module: "readonly",
        require: "readonly",
        process: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        exports: "writable",
        Buffer: "readonly",
        global: "readonly",
        fetch: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        Promise: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        FormData: "readonly",
        Blob: "readonly",
        File: "readonly",
        FileReader: "readonly",
        AbortController: "readonly",
        Image: "readonly",
        HTMLElement: "readonly",
        Element: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        crypto: "readonly",
        MutationObserver: "readonly",
        ResizeObserver: "readonly",
        IntersectionObserver: "readonly",
        Map: "readonly",
        Set: "readonly",
        WeakMap: "readonly",
        WeakSet: "readonly",
        Proxy: "readonly",
        Reflect: "readonly",
        Symbol: "readonly",
        ArrayBuffer: "readonly",
        DataView: "readonly",
        Intl: "readonly",
        JSON: "readonly",
        Math: "readonly",
        Number: "readonly",
        Object: "readonly",
        RegExp: "readonly",
        String: "readonly",
        Date: "readonly",
        Error: "readonly",
        TypeError: "readonly",
        RangeError: "readonly",
        SyntaxError: "readonly",
        Array: "readonly",
        Boolean: "readonly",
        Function: "readonly",
        isNaN: "readonly",
        parseFloat: "readonly",
        parseInt: "readonly",
        decodeURI: "readonly",
        decodeURIComponent: "readonly",
        encodeURI: "readonly",
        encodeURIComponent: "readonly",
        escape: "readonly",
        unescape: "readonly",
        Infinity: "readonly",
        NaN: "readonly",
        undefined: "readonly",
        null: "readonly",
        describe: "readonly",
        it: "readonly",
        test: "readonly",
        expect: "readonly",
        jest: "readonly",
        beforeEach: "readonly",
        afterEach: "readonly",
        beforeAll: "readonly",
        afterAll: "readonly",
      },
    },
    plugins: { "react-hooks": reactHooksPlugin },
    rules: {
      ...js.configs.recommended.rules,
      "react-hooks/rules-of-hooks": "error",
      "react-hooks/exhaustive-deps": "warn",
    },
  },
  // Storybook recommended (via FlatCompat; react-app omitted — use CRA/build for full React linting)
  ...compat.extends("plugin:storybook/recommended"),
];
