/**
 * ChartMind Service - Core service for chart generation and clinical decision support
 * Handles transcription processing, DDX generation, and chart formatting
 */

import firebase from "firebase/compat/app";
import "firebase/compat/functions";

/**
 * ChartMind Service singleton
 */
class ChartMindService {
  constructor() {
    this.defaultSettings = {
      chartFormat: "SOAP",
      includeVitals: true,
      includeDDX: true,
      includeTreatmentPlan: true,
      epidemiologyRegion: "US",
      language: "en-US",
    };
  }

  /**
   * Transcribe audio using OpenAI Whisper
   * @param {Blob} audioBlob - Audio data
   * @param {string} language - Target language code
   * @param {number} temperature - AI temperature (0.1 for accuracy)
   * @param {string} prompt - Previous context prompt
   * @returns {Promise<string>} Transcribed text
   *
   * TODO: Implement Whisper STT via Firebase function
   */
  async whisperSTT(audioBlob, language, temperature = 0.1, prompt = "") {
    console.log("TODO: chartmindService.whisperSTT()", {
      language,
      temperature,
      promptLength: prompt.length,
    });

    // TODO: Uncomment when Firebase function is ready
    // try {
    //   const reader = new FileReader();
    //   const base64Promise = new Promise((resolve) => {
    //     reader.onloadend = () => {
    //       const base64data = reader.result.split(',')[1];
    //       resolve(base64data);
    //     };
    //   });
    //   reader.readAsDataURL(audioBlob);
    //   const audioBase64 = await base64Promise;
    //
    //   const whisperSTTFn = firebase.functions().httpsCallable('chartmindWhisperSTT');
    //   const result = await whisperSTTFn({
    //     audio: audioBase64,
    //     language,
    //     temperature,
    //     prompt,
    //     filename: 'chunk.webm'
    //   });
    //
    //   return result.data?.text || '';
    // } catch (error) {
    //   console.error('Whisper STT failed:', error);
    //   throw error;
    // }

    return "";
  }

  /**
   * Generate a complete medical chart from transcript
   * @param {Object} options - Chart generation options
   * @returns {Promise<string>} Generated chart text
   *
   * TODO: Implement via Firebase function with LLM
   */
  async generateChart({ transcript, audioBlob, selectedPage, settings = {} }) {
    const mergedSettings = { ...this.defaultSettings, ...settings };

    console.log("TODO: chartmindService.generateChart()", {
      transcriptLength: transcript?.length,
      hasAudio: !!audioBlob,
      settings: mergedSettings,
    });

    // TODO: Uncomment when Firebase function is ready
    // try {
    //   const generateChartFn = firebase.functions().httpsCallable('generateMedicalChart');
    //   const result = await generateChartFn({
    //     transcript,
    //     pageId: selectedPage?.id,
    //     settings: mergedSettings,
    //   });
    //
    //   if (result.data?.chart) {
    //     return result.data.chart;
    //   }
    //   return this.generateChartLocally(transcript, mergedSettings);
    // } catch (error) {
    //   console.error('Cloud chart generation failed, using local fallback:', error);
    //   return this.generateChartLocally(transcript, mergedSettings);
    // }

    // For now, use local generation
    return this.generateChartLocally(transcript, mergedSettings);
  }

  /**
   * Local chart generation fallback
   */
  generateChartLocally(transcript, settings) {
    const now = new Date();
    const dateStr = now.toLocaleDateString("en-US", {
      weekday: "long",
      year: "numeric",
      month: "long",
      day: "numeric",
    });
    const timeStr = now.toLocaleTimeString("en-US", {
      hour: "2-digit",
      minute: "2-digit",
    });

    const chiefComplaint = this.extractChiefComplaint(transcript);
    const symptoms = this.extractSymptoms(transcript);
    const vitals = this.extractVitals(transcript);
    const ddx = this.generateDifferentialDiagnosis(
      symptoms,
      settings.epidemiologyRegion
    );

    return `
MEDICAL CHART
Generated by ChartMind
Date: ${dateStr}
Time: ${timeStr}

================================================================================
SUBJECTIVE
================================================================================

Chief Complaint:
${chiefComplaint}

History of Present Illness:
${transcript}

================================================================================
OBJECTIVE
================================================================================

Vital Signs:
${vitals || "Not documented in encounter"}

Physical Examination:
[Physical examination findings to be documented]

================================================================================
ASSESSMENT
================================================================================

${
  ddx
    ? `DIFFERENTIAL DIAGNOSIS:
${ddx}
`
    : ""
}

Primary Assessment:
[Clinical assessment pending review]

================================================================================
PLAN
================================================================================

1. Diagnostic workup as indicated
2. Treatment plan pending diagnosis confirmation
3. Follow-up as clinically appropriate

================================================================================
ADDITIONAL NOTES
================================================================================

This chart was auto-generated from voice recording and requires clinical review.

---
Generated by ChartMind Medical Documentation System
    `.trim();
  }

  /**
   * Extract chief complaint from transcript
   */
  extractChiefComplaint(transcript) {
    const patterns = [
      /complaining of (.+?)(?:\.|,|and|but)/i,
      /came in for (.+?)(?:\.|,|and|but)/i,
      /presenting with (.+?)(?:\.|,|and|but)/i,
      /here for (.+?)(?:\.|,|and|but)/i,
      /chief complaint(?::|is)?\s*(.+?)(?:\.|,|and|but)/i,
    ];

    for (const pattern of patterns) {
      const match = transcript.match(pattern);
      if (match && match[1]) {
        return match[1].trim();
      }
    }

    const firstSentence = transcript.split(/[.!?]/)[0];
    return firstSentence
      ? firstSentence.trim()
      : "Chief complaint not specified";
  }

  /**
   * Extract symptoms from transcript
   */
  extractSymptoms(transcript) {
    const lowerTranscript = transcript.toLowerCase();
    const symptoms = [];

    const symptomPatterns = [
      { pattern: /fever|febrile/, symptom: "fever" },
      { pattern: /cough(?:ing)?/, symptom: "cough" },
      { pattern: /headache/, symptom: "headache" },
      { pattern: /pain/, symptom: "pain" },
      { pattern: /nausea|nauseated/, symptom: "nausea" },
      { pattern: /vomit(?:ing)?|emesis/, symptom: "vomiting" },
      { pattern: /diarrhea|loose stools/, symptom: "diarrhea" },
      { pattern: /fatigue|tired|weak/, symptom: "fatigue" },
      {
        pattern: /shortness of breath|dyspnea|trouble breathing/,
        symptom: "dyspnea",
      },
      { pattern: /chest pain|chest discomfort/, symptom: "chest pain" },
      {
        pattern: /abdominal pain|belly pain|stomach ache/,
        symptom: "abdominal pain",
      },
      { pattern: /sore throat/, symptom: "sore throat" },
      { pattern: /rash/, symptom: "rash" },
      { pattern: /swelling|edema/, symptom: "swelling" },
      { pattern: /dizz(?:y|iness)|vertigo/, symptom: "dizziness" },
    ];

    for (const { pattern, symptom } of symptomPatterns) {
      if (pattern.test(lowerTranscript)) {
        symptoms.push(symptom);
      }
    }

    return symptoms;
  }

  /**
   * Extract vital signs from transcript
   */
  extractVitals(transcript) {
    const vitals = [];

    const bpMatch = transcript.match(
      /blood pressure[:\s]*(\d{2,3})[/\s](\d{2,3})/i
    );
    if (bpMatch) {
      vitals.push(`Blood Pressure: ${bpMatch[1]}/${bpMatch[2]} mmHg`);
    }

    const hrMatch = transcript.match(/(?:heart rate|pulse|hr)[:\s]*(\d{2,3})/i);
    if (hrMatch) {
      vitals.push(`Heart Rate: ${hrMatch[1]} bpm`);
    }

    const tempMatch = transcript.match(
      /(?:temperature|temp)[:\s]*(\d{2,3}\.?\d?)/i
    );
    if (tempMatch) {
      vitals.push(`Temperature: ${tempMatch[1]}°F`);
    }

    const rrMatch = transcript.match(
      /(?:respiratory rate|rr|respirations)[:\s]*(\d{1,2})/i
    );
    if (rrMatch) {
      vitals.push(`Respiratory Rate: ${rrMatch[1]} breaths/min`);
    }

    const o2Match = transcript.match(
      /(?:oxygen|o2 sat|spo2|saturation)[:\s]*(\d{2,3})%?/i
    );
    if (o2Match) {
      vitals.push(`O2 Saturation: ${o2Match[1]}%`);
    }

    return vitals.length > 0 ? vitals.join("\n") : null;
  }

  /**
   * Generate differential diagnosis based on symptoms
   */
  generateDifferentialDiagnosis(symptoms, region = "US") {
    if (symptoms.length === 0) return null;

    const ddxBySymptom = {
      fever: ["Viral infection", "Bacterial infection", "UTI", "Pneumonia"],
      cough: [
        "Upper respiratory infection",
        "Bronchitis",
        "Pneumonia",
        "Asthma exacerbation",
      ],
      headache: ["Tension headache", "Migraine", "Sinusitis", "Hypertension"],
      "abdominal pain": [
        "Gastritis",
        "Appendicitis",
        "Cholecystitis",
        "Gastroenteritis",
      ],
      "chest pain": ["Costochondritis", "GERD", "Anxiety", "Angina"],
      dyspnea: ["Asthma", "COPD exacerbation", "Heart failure", "Pneumonia"],
      nausea: [
        "Gastroenteritis",
        "Food poisoning",
        "Medication side effect",
        "Pregnancy",
      ],
      diarrhea: [
        "Viral gastroenteritis",
        "Food poisoning",
        "IBD",
        "Medication effect",
      ],
    };

    const allDdx = new Set();
    for (const symptom of symptoms) {
      const ddxList = ddxBySymptom[symptom] || [];
      ddxList.forEach((dx) => allDdx.add(dx));
    }

    if (allDdx.size === 0) return null;

    const ddxArray = Array.from(allDdx);
    return ddxArray.map((dx, i) => `${i + 1}. ${dx}`).join("\n");
  }

  /**
   * Generate clinical guidance (MSI) from transcript
   * @param {string} transcript - Current transcript text
   * @param {Object} page - Selected page context
   * @returns {Promise<Object>} Clinical guidance object
   *
   * TODO: Implement via Firebase function with LLM
   */
  async generateClinicalGuidance(transcript, page = null) {
    console.log("TODO: chartmindService.generateClinicalGuidance()", {
      transcriptLength: transcript?.length,
      pageId: page?.id,
    });

    // TODO: Uncomment when Firebase function is ready
    // try {
    //   const generateGuidanceFn = firebase.functions().httpsCallable('generateClinicalGuidance');
    //   const result = await generateGuidanceFn({
    //     transcript,
    //     pageId: page?.id,
    //     specialty: page?.specialty,
    //   });
    //   return result.data;
    // } catch (error) {
    //   console.error('Error generating clinical guidance:', error);
    //   return this.generateLocalGuidance(transcript);
    // }

    return this.generateLocalGuidance(transcript);
  }

  /**
   * Generate local clinical guidance fallback
   */
  generateLocalGuidance(transcript) {
    const symptoms = this.extractSymptoms(transcript);

    return {
      differentialDiagnoses: this.getDifferentialDiagnoses(symptoms),
      suggestedQuestions: this.getSuggestedQuestions(symptoms),
      redFlags: this.identifyRedFlags(transcript),
      recommendations: [],
    };
  }

  /**
   * Get differential diagnoses with likelihood scores
   */
  getDifferentialDiagnoses(symptoms) {
    const ddxMapping = {
      fever: [
        { condition: "Viral infection", likelihood: 70 },
        { condition: "Bacterial infection", likelihood: 50 },
        { condition: "Urinary tract infection", likelihood: 30 },
      ],
      cough: [
        { condition: "Upper respiratory infection", likelihood: 65 },
        { condition: "Bronchitis", likelihood: 45 },
        { condition: "Pneumonia", likelihood: 25 },
      ],
      "abdominal pain": [
        { condition: "Gastritis", likelihood: 55 },
        { condition: "Gastroenteritis", likelihood: 45 },
        { condition: "Appendicitis", likelihood: 20 },
      ],
      "chest pain": [
        { condition: "Costochondritis", likelihood: 50 },
        { condition: "GERD", likelihood: 40 },
        { condition: "Anxiety", likelihood: 30 },
      ],
    };

    const diagnoses = [];
    for (const symptom of symptoms) {
      const dxList = ddxMapping[symptom] || [];
      dxList.forEach((dx) => {
        const existing = diagnoses.find((d) => d.condition === dx.condition);
        if (existing) {
          existing.likelihood = Math.min(95, existing.likelihood + 10);
        } else {
          diagnoses.push({ ...dx });
        }
      });
    }

    return diagnoses.sort((a, b) => b.likelihood - a.likelihood).slice(0, 5);
  }

  /**
   * Get suggested follow-up questions
   */
  getSuggestedQuestions(symptoms) {
    const questions = [];

    if (symptoms.includes("fever")) {
      questions.push("When did the fever start?");
      questions.push("What is the highest temperature recorded?");
      questions.push("Any recent travel or sick contacts?");
    }

    if (symptoms.includes("pain")) {
      questions.push("Can you describe the pain - sharp, dull, burning?");
      questions.push("Does anything make the pain better or worse?");
      questions.push("On a scale of 1-10, how severe is the pain?");
    }

    if (symptoms.includes("cough")) {
      questions.push("Is the cough productive or dry?");
      questions.push("Any blood in the sputum?");
      questions.push("How long have you had this cough?");
    }

    return questions.slice(0, 5);
  }

  /**
   * Identify red flags in transcript
   */
  identifyRedFlags(transcript) {
    const lowerTranscript = transcript.toLowerCase();
    const redFlags = [];

    const redFlagPatterns = [
      {
        pattern:
          /chest pain.*shortness of breath|shortness of breath.*chest pain/,
        flag: "Chest pain with dyspnea - consider cardiac/PE",
      },
      {
        pattern: /worst headache.*life|sudden.*severe.*headache/,
        flag: "Severe sudden headache - consider SAH",
      },
      {
        pattern: /blood in stool|melena|hematemesis/,
        flag: "GI bleeding - urgent evaluation needed",
      },
      {
        pattern: /loss of consciousness|syncope|passed out/,
        flag: "Syncope - evaluate for cardiac cause",
      },
      {
        pattern: /numbness.*weakness|weakness.*numbness|facial droop/,
        flag: "Neurological symptoms - consider stroke",
      },
      {
        pattern: /suicidal|kill myself|end my life/,
        flag: "Suicidal ideation - psychiatric emergency",
      },
      {
        pattern: /allergic.*swelling|anaphylaxis|throat.*closing/,
        flag: "Possible anaphylaxis",
      },
    ];

    for (const { pattern, flag } of redFlagPatterns) {
      if (pattern.test(lowerTranscript)) {
        redFlags.push(flag);
      }
    }

    return redFlags;
  }
}

// Export singleton instance
const chartmindService = new ChartMindService();
export default chartmindService;
