export default [
  "Abdominal Hematoma",
  "Abdominal trauma",
  "Acute adrenal crisis",
  "Acute adrenal insufficiency",
  "Acute angle-closure glaucoma",
  "Acute aortic dissection",
  "Acute aortic regurgitation",
  "Acute aortic stenosis",
  "Acute coronary syndrome",
  "Acute coronary syndrome (acs): heart attack, unstable angina",
  "Acute Epiglottitis",
  "Acute gastroenteritis",
  "Acute Intoxication or Drug Overdose",
  "Acute kidney injury",
  "Acute Labyrinthitis",
  "Acute limb ischemia",
  "Acute liver failure",
  "Acute Liver Injury",
  "Acute mesenteric ischemia",
  "Acute myocardial infarction",
  "Acute myocarditis",
  "Acute necrotizing enterocolitis (in infants)",
  "Acute pancreatitis",
  "Acute porphyria",
  "Acute psychosis",
  "Acute respiratory distress syndrome",
  "Acute Respiratory Distress Syndrome (ARDS)",
  "Acute respiratory distress syndrome (ARDS)",
  "Acute Respiratory Distress Syndrome (ARDS) with Involvement of the Swallowing Reflex",
  "Acute Stress Disorder",
  "Acute urinary retention",
  "Addisonian crisis",
  "Adrenal crisis (addisonian crisis)",
  "Agitation",
  "Alcohol intoxication or overdose",
  "Allergic reactions",
  "Allergic reactions to insect stings",
  "Amyloidosis",
  "Anaphylaxis",
  "Angioedema",
  "Anxiety",
  "Aortic aneurysm",
  "Aortic dissection",
  "Aortic regurgitation",
  "Aortic stenosis",
  "Aplastic anemia",
  "Appendicitis",
  "Arrhythmia",
  "Arrhythmias",
  "Arrhythmogenic right ventricular cardiomyopathy (arvc)",
  "Ascites",
  "Asthma",
  "Asthma exacerbation",
  "Asthma Exacerbation",
  "Atherosclerosis",
  "Atrial fibrillation",
  "Attention deficit hyperactivity disorder (adhd)",
  "Autism spectrum disorder (asd)",
  "Autoimmune encephalitis",
  "Autoimmune hepatitis",
  "Back pain",
  "Bacterial pneumonia",
  "Basal cell carcinoma",
  "Behçet's disease",
  "Bell's palsy",
  "Bell's Palsy",
  "Benign paroxysmal positional vertigo",
  "Benign prostatic hyperplasia (bph)",
  "Biliary colic",
  "Biliary Obstruction",
  "Bipolar disorder",
  "Bladder cancer",
  "Bladder infection",
  "Blepharospasm",
  "Bone cancer",
  "Borderline personality disorder",
  "Bowel Obstruction",
  "Bowel obstruction",
  "Brain aneurysm",
  "Brain tumor",
  "Brain tumor recurrence",
  "Brainstem stroke",
  "Breast cancer",
  "Breast fibroadenoma",
  "Bronchial asthma",
  "Bronchiectasis",
  "Bronchiolitis",
  "Bulimia nervosa",
  "Bursitis",
  "Candidiasis",
  "Carbon monoxide poisoning",
  "Cardiac arrest",
  "Cardiac arrhythmias",
  "Cardiac tamponade",
  "Carpal tunnel syndrome",
  "Cataracts",
  "Celiac disease",
  "Cellulitis",
  "Cerebral aneurysm",
  "Cervical cancer",
  "Cervical dysplasia",
  "Cervical spondylosis",
  "Cervicitis",
  "Chemical burns",
  "Chest trauma",
  "Chiari malformation",
  "Chickenpox",
  "Cholecystitis",
  "Cholelithiasis",
  "Cholera",
  "Chronic bronchitis",
  "Chronic fatigue syndrome",
  "Chronic inflammatory demyelinating polyneuropathy",
  "Chronic inflammatory demyelinating polyneuropathy (cidp)",
  "Chronic kidney disease",
  "Chronic migraines",
  "Chronic obstructive pulmonary disease (copd)",
  "Chronic obstructive pulmonary disease (COPD)",
  "Chronic obstructive pulmonary disease exacerbation",
  "Chronic Pain",
  "Chronic sinusitis",
  "Circadian Rhythm Disorders",
  "Cirrhosis",
  "Cluster headache",
  "Colitis (infectious, ischemic)",
  "Colon cancer",
  "Colorectal cancer",
  "Common cold",
  "Compartment syndrome",
  "Complete heart block",
  "Complex regional pain syndrome (crps)",
  "Congenital heart defect",
  "Congestive heart failure",
  "Conjunctivitis",
  "Constipation",
  "Coronary artery disease",
  "Creutzfeldt-jakob disease",
  "Crohn's disease",
  "Croup",
  "Cushing syndrome",
  "Cushing's syndrome",
  "Cutaneous infections with signs of spreading (cellulitis, necrotizing fasciitis)",
  "Cutaneous lupus erythematosus",
  "Deep vein thrombosis",
  "Dehydration",
  "Delirium",
  "Delirium tremens",
  "Dementia",
  "Dementia exacerbation",
  "Dengue Fever",
  "Dental caries",
  "Depression",
  "Diabetes insipidus",
  "Diabetes mellitus",
  "Diabetic ketoacidosis",
  "Diabetic retinopathy",
  "Difficulty with fine motor skills",
  "Dilated cardiomyopathy",
  "Diphtheria",
  "Disseminated herpes simplex infection",
  "Disseminated intravascular coagulation",
  "Diverticulitis",
  "Drowning",
  "Drug eruptions",
  "Drug overdose",
  "Dry eye syndrome",
  "Dupuytren's contracture",
  "Dysmenorrhea",
  "Dyspareunia",
  "Dyspepsia",
  "Dysphagia",
  "Dysuria",
  "Ear infection",
  "Eating disorders",
  "Ebola Virus Disease",
  "Eclampsia",
  "Ectopic pregnancy",
  "Ectopic Pregnancy",
  "Eczema",
  "Elder abuse",
  "Electric shock",
  "Encephalitis",
  "Endocarditis",
  "Endometriosis",
  "Epilepsy",
  "Erectile dysfunction",
  "Esophageal cancer",
  "Essential tremor",
  "Ewing sarcoma",
  "Eye floaters",
  "Eyelid Myokymia",
  "Facial Bone Fracture",
  "Facial Nerve Compression or Injury",
  "Falls",
  "Febrile seizures",
  "Female infertility",
  "Fibroadenosis",
  "Fibrocystic breast changes",
  "Fibroids",
  "Fibromyalgia",
  "Flatulence",
  "Food poisoning",
  "Foreign body aspiration",
  "Foreign Body Obstruction",
  "Fractures",
  "Fungal infection",
  "Gallbladder cancer",
  "Gallbladder Disease",
  "Gallstones",
  "Gastric cancer",
  "Gastritis",
  "Gastroenteritis",
  "Gastroesophageal reflux disease (gerd)",
  "Gastrointestinal bleeding",
  "Gastrointestinal bleeding, severe",
  "Gastrointestinal stromal tumor (gist)",
  "Generalized anxiety disorder",
  "Genital herpes",
  "Genital warts",
  "Gerd",
  "Gestational diabetes",
  "Gestational trophoblastic disease",
  "Gingivitis",
  "Glaucoma",
  "Goiter",
  "Gout",
  "Graves' disease",
  "Guillain-Barre syndrome",
  "Guillain-barré syndrome",
  "Hand, foot, and mouth disease",
  "Hashimoto's thyroiditis",
  "Head injury with signs of concussion or severe neurological deficits",
  "Head trauma",
  "Hearing loss",
  "Heart attack",
  "Heart failure",
  "Heart failure exacerbation",
  "Heat stroke",
  "Heatstroke",
  "Hemifacial Spasm",
  "Hemochromatosis",
  "Hemolytic anemia",
  "Hemophilia",
  "Hemorrhagic shock",
  "Hemorrhoids",
  "Hepatic encephalopathy",
  "Hepatitis",
  "Hereditary angioedema",
  "Herniated disc",
  "Herpangina",
  "Herpes zoster (shingles)",
  "Hidradenitis suppurativa",
  "High blood pressure",
  "Hip bursitis",
  "Hip fracture",
  "Hirsutism",
  "Hiv/aids",
  "HIV/AIDS",
  "Hodgkin lymphoma",
  "Homicidal ideation",
  "Huntington's disease",
  "Hydrocephalus",
  "Hypercalcemia",
  "Hyperglycemia",
  "Hyperglycemic crisis (dka or hhs)",
  "Hyperglycemic hyperosmolar state",
  "Hyperkalemia",
  "Hyperkalemia, severe",
  "Hypernatremia",
  "Hypernatremia, severe",
  "Hyperparathyroidism",
  "Hypertension",
  "Hypertensive crisis",
  "Hypertensive emergencies",
  "Hypertensive emergency",
  "Hypertensive Emergency",
  "Hyperthermia",
  "Hyperthyroidism",
  "Hypocalcemia",
  "Hypoglycemia",
  "Hypokalemia",
  "Hyponatremia",
  "Hyponatremia, severe",
  "Hypoparathyroidism",
  "Hypothermia",
  "Hypothyroidism",
  "Hypovolemia",
  "Hypovolemic shock",
  "Hypoxic-ischemic encephalopathy (hie)",
  "Hysterectomy",
  "Ichthyosis",
  "Idiopathic Guttate Hypomelanosis",
  "Impetigo",
  "Increased intracranial pressure",
  "Infectious Mononucleosis",
  "Inflammatory bowel disease (ibd)",
  "Inflammatory Process in the Pharynx or Esophagus",
  "Influenza",
  "Inguinal hernia",
  "Insomnia",
  "Internal bleeding",
  "Interstitial cystitis",
  "Interstitial lung disease",
  "Intestinal obstruction",
  "Intoxication",
  "Intracranial hemorrhage",
  "Intracranial hemorrhage (bleeding in the brain)",
  "Intraventricular hemorrhage (ivh)",
  "Invasive fungal infection",
  "Iron-deficiency anemia",
  "Irritable bowel syndrome (ibs)",
  "Kawasaki disease",
  "Kidney cancer",
  "Kidney infection",
  "Kidney stones",
  "Kidney Stones",
  "Labyrinthitis",
  "Lacerations",
  "Lactose intolerance",
  "Laryngitis",
  "Lead poisoning",
  "Leukemia",
  "Leukopenia",
  "Lichen Sclerosus",
  "Liver Abscess",
  "Liver cancer",
  "Liver cirrhosis",
  "Local anesthetic systemic toxicity (last)",
  "Low back pain",
  "Low blood pressure",
  "Lung cancer",
  "Lupus",
  "Lyme disease",
  "Lymphedema",
  "Macular degeneration",
  "Malaria",
  "Malignant hyperthermia",
  "Malignant otitis externa",
  "Malnutrition",
  "Mania",
  "Mania/Hypomania",
  "Massive hemoptysis",
  "Measles",
  "Melanoma",
  "Meniere's disease",
  "Meningitis",
  "Menopause",
  "Menorrhagia",
  "Mesenteric ischemia",
  "Mesenteric Ischemia",
  "Mesothelioma",
  "Migraine",
  "Migraine headaches",
  "Miscarriage",
  "Mitral regurgitation",
  "Mitral stenosis",
  "Molar pregnancy",
  "Mononucleosis",
  "Motion sickness",
  "Multiple myeloma",
  "Multiple sclerosis",
  "Muscle strain or sprain",
  "Muscular dystrophy",
  "Myasthenia gravis",
  "Myasthenic crisis",
  "Myocardial Infarction",
  "Myocardial infarction",
  "Myocardial infarction (heart attack)",
  "Myocardial ischemia during non-cardiac surgery",
  "Myocarditis",
  "Myxedema coma",
  "Nail fungal infection",
  "Narcolepsy",
  "Nasal Fracture",
  "Nasal Polyps",
  "Near-drowning",
  "Necrotizing enterocolitis",
  "Necrotizing enterocolitis (nec)",
  "Necrotizing fasciitis",
  "Neonatal encephalopathy",
  "Neonatal sepsis",
  "Nephrotic syndrome",
  "Neuralgia",
  "Neurofibromatosis",
  "Neuroleptic malignant syndrome",
  "Neurological Disorders (Parkinson's Disease, Multiple Sclerosis)",
  "Neuropathy",
  "Nevus Depigmentosus",
  "Nightmares",
  "Nonalcoholic fatty liver disease",
  "Normal pressure hydrocephalus",
  "Nystagmus",
  "Obsessive-compulsive disorder (ocd)",
  "Obstructed Bowel or Bowel Perforation",
  "Obstructive sleep apnea",
  "Oculogyric Crisis",
  "Open fractures",
  "Opioid addiction",
  "Opsoclonus",
  "Osteoarthritis",
  "Osteoporosis",
  "Ovarian cancer",
  "Ovarian Cyst or Tumor",
  "Ovarian cysts",
  "Ovarian torsion",
  "Overactive bladder",
  "Overdose",
  "Paget's disease",
  "Pancreatic cancer",
  "Pancreatitis",
  "Panic disorder",
  "Paralysis",
  "Paraneoplastic pemphigus",
  "Parkinson's disease",
  "Pelvic inflammatory disease",
  "Pelvic trauma",
  "Peptic ulcer disease",
  "Perforated Peptic Ulcer",
  "Perforated Viscous",
  "Perforated viscus",
  "Pericardial tamponade",
  "Pericarditis",
  "Peripheral artery disease (pad)",
  "Peripheral neuropathy",
  "Peritonitis",
  "Peritonsillar abscess",
  "Peritonsillar Abscess",
  "Pesticide exposure",
  "Peyronie's disease",
  "Pheochromocytoma crisis",
  "Phobias",
  "Pityriasis Alba",
  "Pityriasis Rosea",
  "Placental abruption",
  "Pneumonia",
  "Pneumothorax",
  "Poisoning",
  "Polycystic kidney disease",
  "Polycystic Ovary Syndrome",
  "Polycystic ovary syndrome (pcos)",
  "Polymyalgia rheumatica",
  "Post-traumatic stress disorder (ptsd)",
  "Posterior reversible encephalopathy syndrome (pres)",
  "Postpartum depression",
  "Postpartum hemorrhage",
  "Pre eclampsia",
  "Pre-eclampsia",
  "Premature ejaculation",
  "Premenstrual syndrome (pms)",
  "Pressure ulcers",
  "Prostate cancer",
  "Psoriasis",
  "Psoriatic arthritis",
  "Psychotic Disorders",
  "Pulmonary edema",
  "Pulmonary embolism",
  "Pulmonary Embolism",
  "Pulmonary embolism (pe)",
  "Pulmonary fibrosis",
  "Rabies",
  "Radiation exposure",
  "Raynaud's disease",
  "Reactive arthritis",
  "Rectal cancer",
  "Respiratory distress",
  "Respiratory failure",
  "Restless legs syndrome",
  "Restless Legs Syndrome",
  "Retinal artery occlusion",
  "Retinal detachment",
  "Retinal vein occlusion",
  "Retroperitoneal abscess",
  "Rhabdomyolysis",
  "Rheumatoid arthritis",
  "Ringworm",
  "Rosacea",
  "Rotator cuff injury",
  "Rubella (german measles)",
  "Ruptured abdominal aortic aneurysm",
  "Ruptured Abdominal Aortic Aneurysm",
  "Ruptured ectopic pregnancy",
  "Ruptured ovarian cyst",
  "Salmonella infection",
  "Sarcoidosis",
  "Scarlet Fever",
  "Schizophrenia",
  "Sciatica",
  "Scoliosis",
  "Seborrheic dermatitis",
  "Seizure",
  "Seizure (especially prolonged or status epilepticus)",
  "Seizures",
  "Sepsis",
  "Septic arthritis",
  "Septic shock",
  "Septicemia",
  "Severe allergic skin reactions (anaphylaxis, stevens-johnson syndrome)",
  "Severe asthma attack",
  "Severe burns",
  "Sexually transmitted infections (stis)",
  "Shingles (herpes zoster)",
  "Shoulder impingement syndrome",
  "Side Effects of Certain Medications",
  "Sinus infection",
  "Sinusitis",
  "Sjogren's syndrome",
  "Skin cancer",
  "Sleep apnea",
  "Sleep Apnea",
  "Sleep deprivation",
  "Sleep disorders",
  "Slipped disc (herniated disc)",
  "Smallpox",
  "Snake bites",
  "Social anxiety disorder",
  "Soft tissue injuries",
  "Spinal cord injury",
  "Spinal cord ischemia",
  "Spinal epidural abscess",
  "Spinal stenosis",
  "Splenomegaly",
  "Sprains and strains",
  "Staph infection",
  "Status epilepticus",
  "Stevens-johnson syndrome",
  "Stomach cancer",
  "Strep throat",
  "Streptococcal Pharyngitis",
  "Stroke",
  "Subarachnoid hemorrhage",
  "Subarachnoid hemorrhage (bleeding around the brain)",
  "Subcutaneous panniculitis",
  "Substance abuse",
  "Substance abuse/withdrawal",
  "Substance Use/Withdrawal",
  "Suicidal ideation",
  "Sunburn",
  "Suspected skin cancer",
  "Systemic lupus erythematosus",
  "Takotsubo cardiomyopathy",
  "Temporomandibular joint disorder (tmj)",
  "Tension pneumothorax",
  "Testicular cancer",
  "Tetanus",
  "Thrombocytopenia",
  "Thrush (oral candidiasis)",
  "Thyroid cancer",
  "Thyroid disorders",
  "Thyroid storm",
  "Tinea Versicolor",
  "Tinnitus",
  "Tonsillar Abscess",
  "Tonsillitis",
  "Tourette syndrome",
  "Toxic epidermal necrolysis",
  "Toxic fume inhalation",
  "Toxic megacolon",
  "Toxic shock syndrome",
  "Transient ischemic attack (tia)",
  "Trauma (Fracture, Dislocation)",
  "Traumatic brain injury",
  "Tuberculosis",
  "Tuberculosis (tb)",
  "Typhoid Fever",
  "Ulcerative colitis",
  "Upper airway obstruction",
  "Upper respiratory tract infection",
  "Urethritis",
  "Urinary incontinence",
  "Urinary Obstruction",
  "Urinary Retention",
  "Urinary Tract Infection",
  "Urinary tract infection (uti)",
  "Urinary tract infections",
  "Uterine cancer",
  "Uterine fibroids",
  "Varicose veins",
  "Vasculitis",
  "Vasculitis with rapid progression or affecting vital organs",
  "Venous insufficiency",
  "Vertigo",
  "Vitamin deficiencies",
  "Vitiligo",
  "Volvulus",
  "Von willebrand disease",
  "West nile virus",
  "Whiplash",
  "Whipple's disease",
  "Wilson's disease",
  "Yeast infection",
  "Zika virus",
];
